[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_student_intro_program = "F93GhPc7jhyumu3oEy5Vnej9UKHx4imaPPVDGcNE6Gdn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/flynn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
